version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    args:
      - wait_timeout=28800
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
  admin:
      image : adminer
      restart : always
      depends_on :
         - mysql
      ports :
         - 8000:8080
  redis:
    image: 'redis'
    restart: always
    hostname: redis
    container_name: redis
    ports:
      - '6379:6379'
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "root"
    ports:
      - "5672:5672"
      - "15672:15672"
